INSERT INTO BOOK (BOOK_ID, TITLE, AUTHOR, ISBN, CATEGORY, AVAILABLE) VALUES (-1, 'Las mil y una noches', 'Anonimo', '9788423352883', 'NOVELA LITERARIA', true);
INSERT INTO BOOK (BOOK_ID, TITLE, AUTHOR, ISBN, CATEGORY, AVAILABLE) VALUES (-2, 'Don Quijote de la Mancha', 'Miguel de Cervantes', '9788423355235', 'NOVELA LITERARIA', true);
INSERT INTO BOOK (BOOK_ID, TITLE, AUTHOR, ISBN, CATEGORY, AVAILABLE) VALUES (-3, 'Orgullo y prejuicio', 'Jane Austen', '9788467045642', 'NOVELA LITERARIA', true);
INSERT INTO BOOK (BOOK_ID, TITLE, AUTHOR, ISBN, CATEGORY, AVAILABLE) VALUES (-4, 'Cumbres borrascosas', 'Emily Brontë', '9788408181804', 'NOVELA LITERARIA', true);
INSERT INTO BOOK (BOOK_ID, TITLE, AUTHOR, ISBN, CATEGORY, AVAILABLE) VALUES (-5, 'Moby Dick', 'Herman Melville', '9788408137221', 'NOVELA LITERARIA', true);
